insert into permission(name)
values ('role:create'),
       ('role:read'),
       ('role:update'),
       ('role:delete'),
       ('permission:create'),
       ('permission:read'),
       ('permission:update'),
       ('permission:delete'),
       ('rating:create'),
       ('rating:read'),
       ('rating:update'),
       ('rating:delete'),
       ('product-set:create'),
       ('product-set:read'),
       ('product-set:update'),
       ('product-set:delete'),
       ('product:create'),
       ('product:read'),
       ('product:update'),
       ('product:delete'),
       ('order:create'),
       ('order:read'),
       ('order:update'),
       ('order:delete'),
       ('address:create'),
       ('address:read'),
       ('address:update'),
       ('address:delete'),
       ('category:create'),
       ('category:read'),
       ('category:update'),
       ('category:delete'),
       ('wishlist:create'),
       ('wishlist:read'),
       ('wishlist:update'),
       ('wishlist:delete'),
       ('cart:create'),
       ('cart:read'),
       ('cart:update'),
       ('cart:delete');

insert into role(name)
values ('ADMIN');
insert into role(name)
values ('USER');

insert into role_permission(role_id, permission_id)
values ((select name from role where name = 'USER'), (select name from permission where name = 'rating:read')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'rating:create')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'product-set:read')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'product-set:create')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'product-set:update')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'product-set:delete')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'order:read')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'order:create')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'address:create')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'address:read')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'address:update')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'address:delete')),
       ((select name from role where name = 'USER'), (select name from permission where name = 'category:read'));

insert into role_permission(role_id, permission_id)
values ((select name from role where name = 'ADMIN'), (select name from permission where name = 'role:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'role:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'role:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'role:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'permission:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'permission:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'permission:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'permission:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'rating:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'rating:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'rating:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'rating:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product-set:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product-set:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product-set:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product-set:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'product:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'order:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'order:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'order:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'order:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'address:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'address:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'address:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'address:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'category:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'wishlist:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'wishlist:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'wishlist:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'wishlist:delete')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'cart:create')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'cart:read')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'cart:update')),
       ((select name from role where name = 'ADMIN'), (select name from permission where name = 'cart:delete'));
